#!/bin/bash

set -euo pipefail

readonly awx_username=${AWX_USERNAME:-}
readonly awx_password=${AWX_PASSWORD:-}

if [[ "$TRAVIS_BRANCH" == "develop" ]]; then
    awx_job_id=$AWX_DEVELOP_JOB_ID
elif [[ "$TRAVIS_BRANCH" == "master" ]]; then
    awx_job_id=$AWX_MASTER_JOB_ID
fi

echo https://awx.knstats.com/api/v2/job_templates/$awx_job_id/launch --user "$awx_username:$awx_password"
